apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebius-bionemo-mcp.fullname" . }}
  labels:
    {{- include "nebius-bionemo-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "nebius-bionemo-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
