# =============================================================================
# Platform Module - VPC, Storage, PostgreSQL, Container Registry
# =============================================================================

# -----------------------------------------------------------------------------
# VPC Network (uses existing default network and subnet from the project)
# Set via nebius-env-init.sh -> TF_VAR_network_id / TF_VAR_subnet_id
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Service Account for Storage
# -----------------------------------------------------------------------------
resource "nebius_iam_v1_service_account" "storage" {
  parent_id = var.parent_id
  name      = "${var.name_prefix}-storage-sa"
}

# Get the "editors" group from tenant (grants storage.editor permissions)
# Reference: nebius-solutions-library/anyscale/deploy/bucket_key.tf
data "nebius_iam_v1_group" "editors" {
  name      = "editors"
  parent_id = var.tenant_id
}

# Add the storage service account to the editors group
# This grants the service account permissions to write to storage buckets
resource "nebius_iam_v1_group_membership" "storage_editor" {
  parent_id = data.nebius_iam_v1_group.editors.id
  member_id = nebius_iam_v1_service_account.storage.id
}

resource "nebius_iam_v2_access_key" "storage" {
  parent_id   = var.parent_id
  name        = "${var.name_prefix}-storage-key"
  description = "Access key for OSMO storage bucket"

  # Store secret in MysteryBox instead of returning directly
  # Reference: nebius-solutions-library/modules/o11y/loki.tf
  secret_delivery_mode = "MYSTERY_BOX"

  account = {
    service_account = {
      id = nebius_iam_v1_service_account.storage.id
    }
  }

  depends_on = [nebius_iam_v1_group_membership.storage_editor]
}

# -----------------------------------------------------------------------------
# MysteryBox - Read storage secret (ephemeral, NOT stored in state)
# Reference: nebius-solutions-library/modules/o11y/mysterybox.tf
# Requires Terraform >= 1.10.0
# -----------------------------------------------------------------------------
ephemeral "nebius_mysterybox_v1_secret_payload_entry" "storage_secret" {
  secret_id = nebius_iam_v2_access_key.storage.status.secret_reference_id
  key       = "secret"
}

# -----------------------------------------------------------------------------
# Object Storage Bucket
# -----------------------------------------------------------------------------
resource "nebius_storage_v1_bucket" "main" {
  parent_id         = var.parent_id
  name              = var.storage_bucket_name
  versioning_policy = "ENABLED"
}

# -----------------------------------------------------------------------------
# Shared Filesystem (Filestore)
# -----------------------------------------------------------------------------
resource "nebius_compute_v1_filesystem" "shared" {
  count = var.enable_filestore ? 1 : 0

  parent_id        = var.parent_id
  name             = "${var.name_prefix}-filestore"
  type             = var.filestore_disk_type
  size_bytes       = var.filestore_size_gib * 1024 * 1024 * 1024
  block_size_bytes = var.filestore_block_size_kib * 1024

  lifecycle {
    ignore_changes = [labels]
  }
}

# -----------------------------------------------------------------------------
# PostgreSQL Password (generated + stored in MysteryBox)
# -----------------------------------------------------------------------------
# Password is generated by Terraform and stored in MysteryBox using write-only
# fields, so the password is NOT stored in MysteryBox's Terraform state.
# The random_password IS in state (marked sensitive) — acceptable since state
# is stored encrypted in Nebius Object Storage.
# -----------------------------------------------------------------------------

# Generate PostgreSQL password
resource "random_password" "postgresql" {
  count   = var.enable_managed_postgresql ? 1 : 0
  length  = 32
  special = true
  # Nebius PostgreSQL forbids % @ : / ; [ ] { } | < > , . ?
  override_special = "!#$^&*()-_=+"

  keepers = {
    # Password stays stable unless you taint this resource
    parent_id = var.parent_id
  }
}

# Store PostgreSQL password in MysteryBox (write-only — not in TF state)
resource "nebius_mysterybox_v1_secret" "postgresql_password" {
  count     = var.enable_managed_postgresql ? 1 : 0
  parent_id = var.parent_id
  name      = "${var.name_prefix}-postgresql-password"

  sensitive = {
    secret_version = {
      payload = [{
        key          = "password"
        string_value = random_password.postgresql[0].result
      }]
    }
    version = random_password.postgresql[0].result
  }
}

# Read password back from MysteryBox (ephemeral - NOT stored in state)
ephemeral "nebius_mysterybox_v1_secret_payload_entry" "postgresql_password" {
  count     = var.enable_managed_postgresql ? 1 : 0
  secret_id = nebius_mysterybox_v1_secret.postgresql_password[0].id
  key       = "password"
}

# Local to get the password from MysteryBox
locals {
  postgresql_password = (
    var.enable_managed_postgresql
    ? ephemeral.nebius_mysterybox_v1_secret_payload_entry.postgresql_password[0].data.string_value
    : null
  )
}

# -----------------------------------------------------------------------------
# MEK (Master Encryption Key) — generated + stored in MysteryBox
# -----------------------------------------------------------------------------

# Generate MEK
resource "random_bytes" "mek_key" {
  length = 32

  keepers = {
    parent_id = var.parent_id
  }
}

locals {
  mek_jwk = jsonencode({
    kty = "oct"
    k   = random_bytes.mek_key.base64
    alg = "A256GCM"
    use = "enc"
  })
  mek_json = jsonencode({
    currentMek = "key1"
    meks       = { key1 = base64encode(local.mek_jwk) }
  })
}

# Store MEK in MysteryBox (write-only)
resource "nebius_mysterybox_v1_secret" "mek" {
  parent_id = var.parent_id
  name      = "${var.name_prefix}-mek"

  sensitive = {
    secret_version = {
      payload = [{
        key          = "mek"
        string_value = local.mek_json
      }]
    }
    version = random_bytes.mek_key.base64
  }
}

# -----------------------------------------------------------------------------
# Managed PostgreSQL (MSP) - Nebius Managed Service for PostgreSQL
# Enabled by default for production-ready database service
# -----------------------------------------------------------------------------
resource "nebius_msp_postgresql_v1alpha1_cluster" "main" {
  count      = var.enable_managed_postgresql ? 1 : 0
  parent_id  = var.parent_id
  name       = "${var.name_prefix}-postgresql"
  network_id = var.network_id

  config = {
    version       = var.postgresql_version
    public_access = var.postgresql_public_access

    template = {
      disk = {
        size_gibibytes = var.postgresql_disk_size_gib
        type           = var.postgresql_disk_type
      }
      resources = {
        platform = var.postgresql_platform
        preset   = var.postgresql_preset
      }
      hosts = {
        count = var.postgresql_host_count
      }
    }
  }

  bootstrap = {
    db_name   = var.postgresql_database_name
    user_name = var.postgresql_username
    # NOTE: user_password moved to sensitive block (write-only, not stored in state)
  }

  # Write-only field - password is NOT stored in Terraform state (more secure)
  # Requires Terraform >= 1.11.0
  sensitive = {
    bootstrap = {
      user_password = local.postgresql_password
    }
  }
}

# -----------------------------------------------------------------------------
# Container Registry
# Reference: https://docs.nebius.com/terraform-provider/reference/resources/registry_v1_registry
# Registry endpoint format: cr.<region>.nebius.cloud/<registry-name>
# -----------------------------------------------------------------------------
resource "nebius_registry_v1_registry" "main" {
  count = var.enable_container_registry ? 1 : 0

  parent_id = var.parent_id
  name      = var.container_registry_name != "" ? var.container_registry_name : "${var.name_prefix}-registry"
}
