apiVersion: v1
kind: Pod
metadata:
  name: of2-artifact-holder-t12
  namespace: nim-fast-start
  labels:
    app.kubernetes.io/name: openfold2-artifact-holder
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  enableServiceLinks: false
  nodeSelector:
    kubernetes.io/hostname: computeinstance-e00t12crqg6tw0kz65
  containers:
    - name: holder
      image: docker.io/library/python@sha256:356b0d18f9385f4bdcc673af60e1e64c9d1504952e4ec36ee32044c722a6bc4e
      imagePullPolicy: IfNotPresent
      command: ["/bin/sleep", "86400"]
      volumeMounts:
        - name: checkpoints
          mountPath: /checkpoints
          readOnly: true
        - name: nim-cache
          mountPath: /nim-cache
          readOnly: true
  volumes:
    - name: checkpoints
      persistentVolumeClaim:
        claimName: mlspec-archvteams-2407-ckpt-m3
        readOnly: true
    - name: nim-cache
      persistentVolumeClaim:
        claimName: openfold2-nim-cache
        readOnly: true
