apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: release-name-kuberay
  namespace: default
  labels:
    helm.sh/chart: ray-cluster-1.4.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  rayVersion: 3.0.0.dev0
  enableInTreeAutoscaling: true
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
        dashboard-host: "0.0.0.0"
        metrics-export-port: "9090"
    template:
      metadata:
        labels:
          helm.sh/chart: ray-cluster-1.4.2
          app.kubernetes.io/instance: release-name
          app.kubernetes.io/managed-by: Helm
      spec:
        containers:
        - name: ray-head
          image: rezabah/rayclusterapp-py39-cu128:0.1.2
          imagePullPolicy: IfNotPresent
          
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
          securityContext:
            privileged: true
        volumes:
          - emptyDir: {}
            name: log-volume
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: nebius.com/gpu
                  operator: DoesNotExist
              weight: 1
  workerGroupSpecs:
  - groupName: workergroup
    replicas: 3
    minReplicas: 1
    maxReplicas: 3
    numOfHosts: 1
    rayStartParams: {}
    template:
      metadata:
        labels:
          helm.sh/chart: ray-cluster-1.4.2
          app.kubernetes.io/instance: release-name
          app.kubernetes.io/managed-by: Helm
      spec:
        containers:
        - name: ray-worker
          image: rezabah/rayclusterapp-py39-cu128:0.1.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: 1
            requests:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: 1
          securityContext:
            privileged: true
        volumes:
        - emptyDir: {}
          name: log-volume
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: nebius.com/gpu
                  operator: In
                  values:
                  - "true"
              weight: 1
