apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genmol-native-f7-artifacts
  namespace: nim-fast-start
  labels:
    app.kubernetes.io/name: genmol
    app.kubernetes.io/component: native-artifact
    app.kubernetes.io/part-of: archvteams-2407-faststart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: mlspec-archvteams-2407-io-m3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genmol-native-f7-cache
  namespace: nim-fast-start
  labels:
    app.kubernetes.io/name: genmol
    app.kubernetes.io/component: nim-cache
    app.kubernetes.io/part-of: archvteams-2407-faststart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: compute-csi-default-sc
