apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nebius-npd
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      containers:
      - name: node-problem-detector
        image: registry.gitlab.com/jadnov/nebius/npd:latest
        imagePullPolicy: IfNotPresent
        command:
        - /node-problem-detector
        - --logtostderr
        - --system-log-monitors=/config/kernel-monitor.json,/config/docker-monitor.json
        - --config.custom-plugin-monitor=/config/custom-plugin-gpu-count.json,/config/custom-plugin-gpu-xid.json,/config/custom-plugin-gpu-ecc.json,/config/custom-plugin-gpu-throttle.json
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
      volumes:
      - name: log
        hostPath:
          path: /var/log
      - name: nvidia-bin
        hostPath:
          path: /usr/bin/nvidia-smi
      - name: config
        configMap:
          name: nebius-npd-config
          defaultMode: 0777
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json
          - key: custom-plugin-gpu-count.json
            path: custom-plugin-gpu-count.json
          - key: check_gpu_count.sh
            path: plugin/check_gpu_count.sh
          - key: custom-plugin-gpu-nvlink.json
            path: custom-plugin-gpu-nvlink.json
          - key: check_gpu_nvlink.sh
            path: plugin/check_gpu_nvlink.sh
          - key: custom-plugin-gpu-xid.json
            path: custom-plugin-gpu-xid.json
          - key: check_gpu_xid.sh
            path: plugin/check_gpu_xid.sh
          - key: custom-plugin-gpu-ecc.json
            path: custom-plugin-gpu-ecc.json
          - key: check_gpu_ecc.sh
            path: plugin/check_gpu_ecc.sh
          - key: custom-plugin-ib.json
            path: custom-plugin-ib.json
          - key: check_ib.sh
            path: plugin/check_ib.sh
          - key: custom-plugin-gpu-throttle.json
            path: custom-plugin-gpu-throttle.json
          - key: check_gpu_throttle.sh
            path: plugin/check_gpu_throttle.sh
      serviceAccountName: nebius-npd-sa
      nodeSelector:
        nebius.com/gpu: "true"
