apiVersion: v1
kind: ServiceAccount
metadata:
  name: nebius-npd-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nebius-npd-role
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - patch
    apiGroups:
      - ''
    resources:
      - nodes/status
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nebius-npd-binding
subjects:
- kind: ServiceAccount
  name: nebius-npd-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nebius-npd-role
  apiGroup: rbac.authorization.k8s.io
