apiVersion: v1
kind: Namespace
metadata:
  name: archvteams-2407-k301ud
  labels:
    app.kubernetes.io/part-of: archvteams-2407-k301ud
    ml-specialist.nebius.ai/task: k301ud
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
