apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: archvteams-2407-k301ud-sfs
  labels:
    app.kubernetes.io/part-of: archvteams-2407-k301ud
    ml-specialist.nebius.ai/task: k301ud
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archvteams-2407-k301ud-sfs-checkpoints
  labels:
    app.kubernetes.io/part-of: archvteams-2407-k301ud
    ml-specialist.nebius.ai/task: k301ud
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: archvteams-2407-k301ud-sfs
  hostPath:
    path: /mnt/k301ud-sfs/k301ud/checkpoints
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: ml-specialist.nebius.ai/task
              operator: In
              values:
                - k301ud-sfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-sfs-pvc
  namespace: archvteams-2407-k301ud
  labels:
    app.kubernetes.io/part-of: archvteams-2407-k301ud
    ml-specialist.nebius.ai/task: k301ud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: archvteams-2407-k301ud-sfs
  volumeName: archvteams-2407-k301ud-sfs-checkpoints
