apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nebius-npd-role
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - patch
    apiGroups:
      - ''
    resources:
      - nodes/status
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events 