apiVersion: v1
kind: ConfigMap
metadata:
  name: nebius-npd-config
  namespace: {{ .Values.global.namespace }}
data:
  kernel-monitor.json: |-
    {{- .Files.Get "files/npd/tests/kernel-monitor.json" | nindent 4 }}
  docker-monitor.json: |-
    {{- .Files.Get "files/npd/tests/docker-monitor.json" | nindent 4 }}
  custom-plugin-gpu-count.json: |-
    {{- .Files.Get "files/npd/tests/custom-plugin-gpu-count.json" | nindent 4 }}
  check_gpu_count.sh: |-
    {{- .Files.Get "files/npd/tests/check_gpu_count.sh" | nindent 4 }}
  custom-plugin-gpu-nvlink.json: |-
    {{- .Files.Get "files/npd/tests/custom-plugin-gpu-nvlink.json" | nindent 4 }}
  check_gpu_nvlink.sh: |-
    {{- .Files.Get "files/npd/tests/check_gpu_nvlink.sh" | nindent 4 }}
  custom-plugin-gpu-xid.json: |-
    {{- .Files.Get "files/npd/tests/custom-plugin-gpu-xid.json" | nindent 4 }}
  check_gpu_xid.sh: |-
    {{- .Files.Get "files/npd/tests/check_gpu_xid.sh" | nindent 4 }}
  custom-plugin-gpu-ecc.json: |-
    {{- .Files.Get "files/npd/tests/custom-plugin-gpu-ecc.json" | nindent 4 }}
  check_gpu_ecc.sh: |-
    {{- .Files.Get "files/npd/tests/check_gpu_ecc.sh" | nindent 4 }}
  custom-plugin-ib.json: |-
    {{- .Files.Get "files/npd/tests/custom-plugin-ib.json" | nindent 4 }}
  check_ib.sh: |-
    {{- .Files.Get "files/npd/tests/check_ib.sh" | nindent 4 }}
  custom-plugin-gpu-throttle.json: |-
    {{- .Files.Get "files/npd/tests/custom-plugin-gpu-throttle.json" | nindent 4 }}
  check_gpu_throttle.sh: |-
    {{- .Files.Get "files/npd/tests/check_gpu_throttle.sh" | nindent 4 }}