apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMk1ETXhOekV4TURFMU4xb1hEVE0yTURNeE5ERXhNRFkxTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0NxCjhOMzdYT20rVGx1OGp1a0RZWmhuODdjcTNBQ0dOQW9CWFlSVjlKUjdyR2lTR3R2QWQ4Nnc4SmNFWFZOSFErV3AKdCsyNmNCTDhVV25iclFyL05INytuK0NOT3d5S1lMcm1tbXRuS0Y1T05NZ3ZxSzVHbmpMREptNll0c1Zrd0xNUgo2VjB5ZWpCbWw0TjBodkwrVXBTV2dra3c4b3pCRlFRSUR0OGxSRDRsZEJPbkllZ3RzL3IySHViY2FnK2tJeVRFCjF5aVJsSTdzYnJzaEtRT05MdmFOb0VQNGlESmxKdm16Y1UrS0hiR1kxdHBqWFZ0bmlLbXg4TGNlY2tJT01uUWoKTFJMNFJmd3R2RmthdTlzcnV0OHowMUVrK3dzQ3FnQTNySUZnL1ZzQitkQ1pPR2h3cHlEWUdJSVJRRFV4TS93MQpjVjBOaEptUWw0eHpXeVFsdU1jQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGRHorbUVKblUxWlVLd0d3eDJydEN1eDJlTnBrTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQlA5di9wQm50M3F6T2wvZURCZ3hLT2lRN3FSRTJBZ2dFa0RXQkM1QnZrcnY0dgp2T3RiaFh0VmxjNlc5S1YvTUptTXgwdVlCNHYrUFhpUFhwQTc2TVJlK3E2aGd1WnJNdFpLcHlxTEhnSXZybzh4ClV2UWw5Z3U1dXRxdnQyTk1FVWM4RERlQTJOQmM4dW9GTFIyMlM2M2QwL3ZhayszV1JOQ01Wczc1eE5YNTBXREsKRC9uOFJxYnEvZ21zbmJjYUFleElXV2svOUhCNlllQ2NBME9ZK0hPWDliVGxERmdUL1F2NGppdUdSdXR5cDd4bApoeW5aTVJWcEFsK2tUMTlCT29yd2laelVWYm1UbGtPd1plZXVZVnd1bmNKQmFYcGpCT0pIMllWY1ZORXJsdS9lCnh1STZwcEhhUnFrY2t6SklteUQ4Q1R6K2NjbUljUGcvZTl2WTF4T3EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://sv.mk8scluster-e00pq5tsd20y6rebt1.mk8s.prod.man.nbhost.net:443
  name: npc-mk8s-k8s-karpenter-test
contexts:
- context:
    cluster: npc-mk8s-k8s-karpenter-test
    user: npc-mk8s-k8s-karpenter-test
  name: npc-mk8s-k8s-karpenter-test
current-context: npc-mk8s-k8s-karpenter-test
kind: Config
preferences: {}
users:
- name: npc-mk8s-k8s-karpenter-test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - mk8s
      - v1
      - cluster
      - get-token
      - --profile
      - man-prod
      - --format
      - json
      command: /home/elemir/.config/newbius/bin/npc
      env: null
      provideClusterInfo: false
