apiVersion: v1
kind: Pod
metadata:
  name: boltz2-cache-holder-r3-t12
  namespace: nim-fast-start
  labels:
    app.kubernetes.io/name: boltz2-cache-holder
    app.kubernetes.io/part-of: archvteams-2407-faststart
spec:
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Never
  nodeName: computeinstance-e00t12crqg6tw0kz65
  containers:
    - name: holder
      image: docker.io/library/python@sha256:356b0d18f9385f4bdcc673af60e1e64c9d1504952e4ec36ee32044c722a6bc4e
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sleep
        - "86400"
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      volumeMounts:
        - name: nim-cache
          mountPath: /nim-cache
          readOnly: true
  volumes:
    - name: nim-cache
      persistentVolumeClaim:
        claimName: boltz2-nim-cache-native-f7-r3
        readOnly: true
