runtime:
  type: containerd

storage:
  type: pvc
  accessMode: agentMount
  pvc:
    create: false
    name: mlspec-archvteams-2407-ckpt-m3
    basePath: /checkpoints

daemonset:
  image:
    repository: cr.eu-north1.nebius.cloud/e00ffw8yqnrrd507t9/archvteams-2407-k301ud/snapshot-agent
    tag: f7f37be-criu91d552-generic-compliant-20260818
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: archvteams-2407-registry-pull
  snapshotLogLevel: info
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "4"
      memory: 4Gi
  nodeSelector:
    kubernetes.io/hostname: computeinstance-e00t12crqg6tw0kz65
    nvidia.com/gpu.present: null
  tolerations: []
  initContainer:
    image: busybox:1.36.1
    imagePullPolicy: IfNotPresent

seccomp:
  deploy: true

rbac:
  create: true
  namespaceRestricted: true

config:
  restore:
    restoreTimeoutSeconds: 900
  criu:
    imageIoMode: direct
    leaveRunning: true
    tcpClose: false
    tcpEstablished: true
    manageCgroupsMode: soft
    mntnsCompatMode: false
