apiVersion: v1
kind: Pod
metadata:
  name: rfdiffusion-native-f7-image-holder-nkpcb
  namespace: nim-fast-start
  labels:
    app.kubernetes.io/name: rfdiffusion
    app.kubernetes.io/component: image-cache-holder
    app.kubernetes.io/part-of: archvteams-2407-faststart
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  enableServiceLinks: false
  runtimeClassName: nvidia
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - gpu-node-c.example.invalid
  imagePullSecrets:
    - name: nvcrio-cred
  containers:
    - name: holder
      image: nvcr.io/nim/ipd/rfdiffusion@sha256:15e40e466d8ebe9a53f1feea599373720428c9de65da750bf4271c96ec35ceb4
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sleep
      args:
        - "2147483647"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
