#!/usr/bin/env bash

# Source this file before running the examples, or override values directly in
# the shell. The Nebius CLI profile supplies tenant/project authentication.

export SERVERLESS_SUBNET_NAME="${SERVERLESS_SUBNET_NAME:-default-subnet}"
export SERVERLESS_SUBNET_ID="${SERVERLESS_SUBNET_ID:-}"

export SERVERLESS_JOB_NAME="${SERVERLESS_JOB_NAME:-sls-nvidia-smi}"
export SERVERLESS_JOB_IMAGE="${SERVERLESS_JOB_IMAGE:-nvidia/cuda:13.1.1-runtime-ubuntu24.04}"
export SERVERLESS_JOB_PLATFORM="${SERVERLESS_JOB_PLATFORM:-gpu-l40s-a}"
export SERVERLESS_JOB_PRESET="${SERVERLESS_JOB_PRESET:-1gpu-8vcpu-32gb}"
export SERVERLESS_JOB_TIMEOUT="${SERVERLESS_JOB_TIMEOUT:-1h}"

export SERVERLESS_ENDPOINT_NAME="${SERVERLESS_ENDPOINT_NAME:-sls-nginx-auth}"
export SERVERLESS_ENDPOINT_PLATFORM="${SERVERLESS_ENDPOINT_PLATFORM:-cpu-d3}"
export SERVERLESS_ENDPOINT_PRESET="${SERVERLESS_ENDPOINT_PRESET:-4vcpu-16gb}"

export SERVERLESS_VLLM_ENDPOINT_NAME="${SERVERLESS_VLLM_ENDPOINT_NAME:-sls-vllm-chat}"
export SERVERLESS_VLLM_MODEL_ID="${SERVERLESS_VLLM_MODEL_ID:-Qwen/Qwen3-0.6B}"
export SERVERLESS_VLLM_IMAGE="${SERVERLESS_VLLM_IMAGE:-vllm/vllm-openai:v0.18.0-cu130}"
export SERVERLESS_VLLM_PLATFORM="${SERVERLESS_VLLM_PLATFORM:-gpu-l40s-a}"
export SERVERLESS_VLLM_PRESET="${SERVERLESS_VLLM_PRESET:-1gpu-8vcpu-32gb}"
export SERVERLESS_VLLM_SHM_SIZE="${SERVERLESS_VLLM_SHM_SIZE:-16Gi}"

export SERVERLESS_FINE_TUNE_JOB_NAME="${SERVERLESS_FINE_TUNE_JOB_NAME:-sls-qwen-lora}"
export SERVERLESS_FINE_TUNE_BUCKET="${SERVERLESS_FINE_TUNE_BUCKET:-fine-tuning-axolotl}"
export SERVERLESS_FINE_TUNE_IMAGE="${SERVERLESS_FINE_TUNE_IMAGE:-docker.io/axolotlai/axolotl:main-20260309-py3.11-cu128-2.9.1}"
export SERVERLESS_FINE_TUNE_PROFILE="${SERVERLESS_FINE_TUNE_PROFILE:-l40s-a}"
export SERVERLESS_FINE_TUNE_PLATFORM="${SERVERLESS_FINE_TUNE_PLATFORM:-}"
export SERVERLESS_FINE_TUNE_PRESET="${SERVERLESS_FINE_TUNE_PRESET:-}"
export SERVERLESS_FINE_TUNE_DISK_SIZE="${SERVERLESS_FINE_TUNE_DISK_SIZE:-450Gi}"
