name: "Soperator Terraform"

on:
  pull_request:
    paths:
      - "soperator/**"
  push:
    branches:
      - main
    paths:
      - "soperator/**"

permissions:
  contents: read

jobs:
  terraform-check:
    name: "Soperator Terraform Checks"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: soperator

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "v1.12.2"

      # fmt check + init/validate of all modules and installations + module tests
      - name: Terraform Check - Modules and Installations
        run: make terraform-check
